#=====================# [설정 변경 O]
#제한 시간 (기본값 10 )
Time: 10

#라운드 (기본값 10)
Round: 10









#=======================================# [설정 변경 X]

#현재 소유권을 가지고 있는 플레이어 (기본값 null) [설정 변경 x]
Owner:

#현재 게임이 진행중인 상태 (기본값 false) [설정 변경 x]
Game: false

#난수 값. (기본값 설정 X) [설정 변경 x]
Count: 0

#현재 문구 (기본값 null) [설정 변경 x]
Text:
